language: python
python:
    - "2.7"
env:
    - CKANVERSION=master
    - CKANVERSION=2.2-dgu
services:
    - redis-server
    - rabbitmq
install:
    - bash bin/travis-build.bash
script: bash bin/travis-run.sh
